### ISSUE TITLE
2021 Season Support?

### ISSUE THREAD

**Issue by joshuapinter** [darxmorph/VideoDownloader-OSX#1]
Hey, this is a great app - thanks for making it!

Trying to download some videos from the 2021 season and it's not recognizing the URL as being valid. For example: 

1. https://f1tv.formula1.com/page/4333/formula-1-bahrain-grand-prix-2022
2. https://f1tv.formula1.com/detail/1000005265/inside-story-alonso-s-sparkling-return-to-the-podium

As well as some archive full race replays, like;
https://f1tv.formula1.com/detail/1000001732/1998-belgian-grand-prix?action=play

Any plans for adding support here? 

Super valuable when jumping on a plane, etc. (literally what I'm doing in about 30 minutes lol)

Thanks!

Joshua

**Comment by darxmorph** [comment]
Hope your flight went well!

So those URLs are for F1TV which is paid. Unfortunately I don't have any plans to support them anytime soon, but you can check out the following projects:

- https://github.com/robvdpol/RaceControl - Windows-only but the easiest to use.
- https://github.com/SoMuchForSubtlety/f1viewer - Doesn't have a download feature but you can add a custom command to do it.

The only videos which are supposed to work are the publicly accessible ones on www.formula1.com, although the macOS version has been broken for a while (to be fixed soon™).

**Comment by joshuapinter** [comment]
@darxmorph Thanks for the reply! Flight went fine, albeit without any F1TV. Lol.

Okay, that makes perfect sense. I've used `f1viewer` previously on the Fire Stick before F1 had their own app for it so I'll check that out in the future. Meanwhile, I'll get by without F1 on my flights - I should probably be working anyway! Lol. 

Good luck with the To Be Fixed Soon To-Do list. :)
